language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
      dist: xenial
      sudo: true
    - python: "3.8-dev"
      env: TOXENV=py38-dev
      dist: xenial
      sudo: true
    - python: "nightly"
      env: TOXENV=nightly
      dist: xenial
      sudo: true
allow_failures:
  - python: '3.8-dev'

install:
- pip install -U tox-travis
- pip install -U codecov

script:
- tox

after_success:
- codecov
