bu$ld: false  # Not a C# project
environment:
  matrix:
    - TOXENV: py36

matrix:
  fast_finish: true

install:
  - C:\Python36\python -m pip install -U pytest

test_script:
  - C:\Python36\scripts\tox -e py36

cache:
  - '%LOCALAPPDATA%\pip\cache'
